locale: 'zh_Hant'
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:
  - name: 'post'
    label: 'Post'
    folder: 'content/posts'
    create: true
    fields:
      - { label: '文章標題', name: 'title', widget: 'string' }
      - { label: '發佈時間', name: 'date', widget: 'datetime' }
      - { label: '主打', name: 'featured', widget: 'boolean', required: false }
      - { label: '精選', name: 'tranding', widget: 'boolean', required: false }
      - { label: '標籤', name: 'tags', widget: 'string' }
      - { label: '閱讀時間', name: 'readTime', widget: 'string' }
      - { label: '縮圖', name: 'thumbnail', widget: 'image', choose_url: true }
      - { label: '文章主圖', name: 'featureImage', widget: 'image', choose_url: true }
      - { label: '內文', name: 'body', widget: 'markdown' }
