backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:
  - name: 'post'
    label: 'Post'
    folder: 'content/posts'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'string' }
      - { label: 'Read Time', name: 'readTime', widget: 'string' }
      - { label: 'Thumnail', name: 'thumbnail', widget: 'image', choose_url: true }
      - { label: 'Banner', name: 'featureImage', widget: 'image', choose_url: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }